

<input type="checkbox" id="privacidad" />
<label for="privacidad">
	He leído y acepto las Condicione del servicio y la Politica de CCM
</label>


<div id="el_modal" class="modal modal-fixed-footer">
	<div class="modal-content">
		<h5>Aviso de Privacidad</h5>
		<p><b>INTRODUCCIÓN</b></p>
		<p>El presente documento constituye el “Aviso de Privacidad” de Comercializadora Colegio México.</p>
		<p>Con fundamento en los artículos 8, 15, 16, 18 y 36 de la Ley Federal de Protección de Datos Personales en Posesión de Particulares hacemos de su conocimiento que Tienda CCM, Con domicilio en San Borja 1011 Col. Del Valle Centro Delegación Benito Juárez, Cd de México CP 03100, es responsable de recabar sus datos personales, del uso que se le dé a los mismos y de su protección.</p>
		<p>Este Aviso especifica el tipo de datos que Tienda CCM recolecta, los fines para los cuales lleva a cabo el tratamiento de los mismos, así como los medios para ejercer los derechos con que cuenta el titular al respecto.</p>
		<p>Las condiciones contenidas en el presente son aplicables a la información que se recaba a nombre de y por CCM por cualquier medio, incluyendo el sitio web de Tienda CCM  (en adelante “CCM”).</p>
		<p>Los sitios vinculados desde los sitios Web de CCM (incluso los de otras filiales) y los que se pueden acceder a través de carteles publicitarios pudieran tener otras políticas, por lo que le rogamos revisar las Políticas y/o Avisos de Privacidad de cada uno de esos sitios Web.</p>
		<p>CCM no requiere, en principio, que usted proporcione Datos Personales (por ejemplo al visitar y utilizar los sitios Web de CCM), sin embargo, para participar en ciertas actividades será necesario que proporcione algunos de sus Datos Personales.</p>
		<p><b>INFORMACIÓN QUE SE RECABA</b></p>
		<p><u>1) Datos Personales</u></p>
		<p>CCM pudiera tratar Datos Personales, es decir, información que lo identifica o lo hace identificable. Estos Datos Personales pueden ser: nombre, género, correo electrónico, domicilio postal, domicilio de entrega (en caso de pedidos), número de teléfono, número de identificación de documento, fecha de nacimiento o algún identificador persistente (por ejemplo, un número de cliente guardado en una cookie) asociado con los Datos Personales, datos de pago, (tales como, número de tarjeta de crédito, vigencia y código de seguridad), datos de facturación. Estos datos personales usted los proporciona voluntariamente al decidir participar en boletines, foros, “chat rooms”, concursos, registrarse para cierta actividad, descargar cierto software y participar en otras actividades que CCM ofrezca, así como cuando decide comprar nuestros productos y/o servicios y requiere soporte técnico. CCM podrá interrelacionar la información que usted proporciona a CCM con otra información que usted haya voluntariamente proporcionado a terceros. Lo anterior, a fin de adaptar nuestro sitio Web, nuestros productos o servicios y nuestras promociones a sus preferencias.</p>
		<p><u>2) Información no personal</u></p>
		<p>El servidor de CCM reconoce y almacena automáticamente de todo visitante, información tal como la combinación dirección IP/nombre de dominio del visitante, y cualquier sitio Web que haga referencia a nuestro sitio. Para ello, CCM puede usar varias tecnologías, hoy disponibles o que puedan desarrollarse. Esta información es utilizada para seguir los esquemas de tráfico de nuestros sitios y lograr optimizar la utilización de nuestros sitios Web. Su computadora proporciona automáticamente esta información cada vez que usted inicia sesión, a menos que haya activado alguna tecnología que bloquee estas opciones.</p>
		<p>CCM utiliza “cookies”, así como otros medios y mecanismos tecnológicos cuando usted visita los sitios Web de CCM, los anuncios que aparecen en ellos o cuando usa los servicios de los sitios Web de CCM. Dichas “cookies” permiten almacenar cierta información en la computadora del usuario y personalizar la experiencia de éste, teniendo en cuenta sus intereses y preferencias, o simplemente facilitar el inicio de sesión para usar los servicios. La mayoría de los exploradores le permitirán eliminar el uso de cookies, bloquear la aceptación de las cookies o recibir una advertencia antes de almacenar cookies. Es posible que si bloquea las cookies, usted no pueda restablecer sus preferencias ni valores de personalización previamente especificados y nuestra capacidad de personalizar su experiencia en línea sería limitada. Le rogamos consultar las instrucciones de su explorador o pantalla de “ayuda” para averiguar más respecto a las cookies.</p>
		<p>CCM podrá también recopilar y almacenar información agregada anónima sobre los visitantes de nuestros sitios Web. CCM puede compartir dicha información con los anunciantes, socios de negocio, patrocinadores y otros terceros para comunicarles, por ejemplo: el porcentaje de visitantes masculinos/femeninos o el porcentaje de visitantes pertenecientes a una edad determinada. CCM podrá también recabar información anónima sobre las aficiones de los visitantes, sus intereses, hábitos de compra, preferencias musicales y otros similares. Esta información puede utilizarse para adaptar el contenido de nuestros sitios Web, así como la publicidad que en ellos se incluye y hacer de su visita una mejor experiencia.</p>
		<p><b>USOS Y FINALIDADES DE SUS DATOS PERSONALES</b></p>
		<p>Los Datos Personales que proporcione voluntariamente a CCM al decidir participar en boletines, foros, “chat rooms”, concursos, registrarse para cierta actividad, descargar cierto software y participar en otras actividades que CCM ofrezca serán utilizados para las finalidades que se le indican en el Aviso de Privacidad que se ponga a su disposición.</p>
		<p>Los Datos Personales que proporcione a CCM cuando decide comprar nuestros productos y/o solicitar nuestros servicios serán tratados, además de para cumplir con las obligaciones derivadas de la relación que con usted pudiera crearse para las siguientes finalidades necesarias:</p>
		<p>1.Llevar a cabo la facturación de los productos que adquiera o los servicios que contrate.<br> 
		2. Entregar nuestros productos y prestar los servicios que solicita.<br>
		3. Hacer efectiva la garantía de los productos que usted haya adquirido, de conformidad con la póliza respectiva.<br>
		4. Dar seguimiento a algún problema que haya surgido respecto a pedidos y/o entrega de productos o la prestación de los servicios contratados.<br>
		5 .Cumplir con las obligaciones derivadas de la revisión, diagnóstico y/o reparación de los productos.<br>
		6. Proporcionar soporte técnico.<br>
		7. Proporcionarle información para que su producto pueda ser ingresado a nuestros Centros de Servicio.<br>
		8. Enviarle comunicaciones necesarias en relación con los productos y/o servicios que haya adquirido.<br>
		9. Para inscribirlo en los Programas de Lealtad cuando éstos resulten aplicables.</p>
		<p>Sus Datos Personales también podrán tratarse para cumplir con las siguientes finalidades secundarias:</p>
		<p>1. Proporcionarle información sobre productos, servicios, promociones, concursos, certámenes u otras actividades o propuestas de interés de CCM y sus empresas subsidiarias, afiliadas y su casa matriz.<br>
		2. Solicitarle información para efectos de investigación de mercado.<br>
		3. Para que usted participe en promociones, concursos, certámenes u otras actividades de CCM, así como para contactarlo con tales fines.<br>
		4. Para solicitarle que responda algunas encuestas de satisfacción respecto a nuestros productos y servicios.<br>
		5. Para contactarlo en relación con el resultado de las evaluaciones que haya realizado respecto de los productos y servicios de CCM o algún otro tema.<br>
		6. En general, para hacerle llegar información de CCM y sus empresas subsidiarias y afiliadas y la casa matriz, con fines publicitarios y de promoción.</p>
		<p>En caso que sus Datos Personales pretendan ser utilizados para una finalidad distinta a las anteriores, CCM le notificará por correo electrónico o por teléfono, a fin de obtener su consentimiento para el tratamiento de sus Datos Personales de acuerdo a las nuevas finalidades. De no recibir su consentimiento, para los casos en que es necesario, CCM no utilizará sus Datos Personales.</p>
		<p>Usted podrá manifestar si desea que lo contactemos marcando la casilla correspondiente al momento de proporcionar sus Datos Personales o por otros medios, tales como, el envío de un correo electrónico con esa petición a: contacto@tiendaccm.mx</p>
		<p><b>DATOS PERSONALES RELATIVOS A MENORES DE EDAD</b></p>
		<p>(a saber, la edad mínima para usuarios de Internet de acuerdo a la legislación aplicable)</p>
		<p>Un menor de edad no debe proporcionar Datos Personales en los sitios Web de CCM o al participar en concursos, certámenes u otras actividades organizadas por CCM y/o cualquier tercero contratado por CCM y/o cualquiera de sus empresas subsidiarias, afiliadas y su casa matriz, sin el conocimiento o autorización de sus padres o tutores. Si CCM detecta que usted es menor de edad, no tratará sus Datos Personales sin el consentimiento previo de sus padres o tutores, salvo que ello esté permitido por la ley.</p>
		<p>Para los concursos que CCM pudiera organizar, solicitará que cada concursante proporcione su año de nacimiento y otros Datos Personales, como nombre, dirección, número de teléfono y correo electrónico. Si el año proporcionado indica que el concursante pudiera ser menor de edad, el concursante no podrá participar sin la previa autorización por escrito de sus padres o tutores y la información proporcionada será eliminada de las bases de datos de CCM.</p>
		<p>En ocasiones se puede pedir al menor de edad que proporcione los datos de contacto de alguno de sus padres o tutores. Dicha información será utilizada únicamente para ponerse en contacto con los padres o tutores y notificarles de las prácticas de CCM al tratar Datos Personales de menores de edad, así como para recabar consentimiento a fin de que el menor participe en una de las actividades promocionales de CCM o en alguno de los sitios Web de CCM. Los padres o tutores de un menor cuyos Datos Personales hayan sido recabados pueden solicitar tener acceso a dicha información, rectificarla o corregirla, hacer que la misma se elimine de las bases de datos de CCM y prohibir la recolección y uso ulterior de dichos Datos Personales. Para obtener más información sobre estos procedimientos, le rogamos comunicarse con CCM en la forma indicada abajo.</p>
		<p><b>COMUNICACIÓN DE PATOS PERSONALES</b></p>
		<p>CCM no compartirá, sin su consentimiento previo, sus Datos Personales con terceros, nacionales o extranjeros, fuera del grupo de nuestras compañías, tales como: empresas afiliadas, corporaciones, cualquier otra empresa en la que nuestra compañía posea directa o indirectamente más del 50% de las acciones en circulación (todas ellas pudiendo estar en México o en el extranjero), salvo (a) que la ley o un mandato judicial así lo requieran; (b) que la información deba compartirse con contratistas de CCM para llevar a cabo las operaciones internas y cumplir con las finalidades descritas (por ejemplo para enviarle un artículo promocional solicitado por usted en el sitio, hacer entrega de pedidos, almacenar la información física o electrónicamente); (c) para proteger los derechos o bienes de CCM o de sus clientes; (d) que dicha transferencia esté prevista en la Ley Federal de Protección de Datos Personales en Posesión de los Particulares. Hemos requerido o requeriremos que nuestros contratistas acuerden usar sus Datos Personales sólo para el fin de llevar a cabo las operaciones para las cuales fueron contratados.</p>
		<p><b>SEGURIDAD</b></p>
		<p>CCM ha adoptado las medidas de seguridad, administrativas, técnicas y físicas, necesarias para proteger sus Datos Personales contra daño, pérdida, alteración, destrucción o el uso, acceso o tratamiento no autorizado.</p>
		<p>El acceso a sus Datos Personales, en poder de CCM, se limitará a las personas que necesiten tener acceso a dicha información, con el propósito de llevar a cabo las finalidades identificadas.</p>
		<p>En caso que al momento de proporcionar sus Datos Personales a CCM se le asigne un nombre de usuario y contraseña, usted será responsable de que dicha información se mantenga confidencial. Le sugerimos no compartir esta información con nadie. Si comparte su equipo, procure siempre cerrar la sesión antes de salir de un sitio o servicio a fin de evitar que terceros no autorizados puedan acceder a su información.</p>
		<p><b>ALMACENAMIENTO DE LA INFORMACIÓN</b></p>
		<p>Los sitios Web de CCM se hospedan y mantienen en Estados Unidos de América, Canadá, México y otros países. Toda información recabada por CCM o proporcionada por usted a CCM mediante el uso de los sitios Web de CCM será enviada y almacenada por, o para, CCM en Estados Unidos de América, Canadá, México y otros países. Al proporcionar Datos Personales en los sitios Web de CCM, los usuarios, incluso y sin limitarse a, los de estados pertenecientes a la Unión Europea y los de cada una de las jurisdicciones de América Latina, entienden plenamente y consienten inequívocamente que tal información se recolecte, transfiera, procese y almacene en Estados Unidos de América para los fines que le fueron informados.</p>
		<p><b>DERECHOS QUE LE CORRESPONDEN AL TITULAR DE DATOS PERSONALES</b></p>
		<p>Usted como titular de Datos Personales podrá, solicitar, por sí o a través de un representante, ante el Departamento de Protección de Datos Personales de CCM el acceso, rectificación, cancelación u oposición (derechos ARCO), respecto de sus Datos Personales. Asimismo, podrá en todo momento revocar el consentimiento que haya otorgado, y que fuere necesario, para el tratamiento de sus Datos Personales y limitar el uso o divulgación de los mismos. Para ello, deberá enviar a o al correo electrónico contacto@tiendaccm.mx su solicitud, en los términos que establece la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (a saber, con: su nombre y domicilio u otro medio para comunicarle la respuesta a su solicitud; acompañando los documentos que acrediten su identidad o, en su caso, la representación legal; la descripción clara y precisa de los datos personales respecto de los que se busca ejercer alguno de los derechos y cualquier otro elemento o documento que facilite la localización de los datos personales). Para fácil referencia, le comunicamos lo siguiente:</p>
		<p>+ El derecho de Acceso consiste en.- que se le informe cuáles de sus Datos Personales están contenidos en las bases de datos de CCM y para qué se utilizan, el origen de dichos datos, las comunicaciones que se hayan realizado con los mismos.<br> 
		+ La obligación de acceso se dará por cumplida cuando: i) los datos se pongan a disposición del titular de los datos personales o bien, ii) mediante la expedición de copias simples, medios magnéticos, ópticos, sonoros, visuales, holográficos, documentos electrónicos o cualquier otro medio o tecnología que se considere adecuada.<br>
		+ El derecho de Rectificación consiste en.- que se corrijan o actualicen sus Datos Personales en caso de que sean inexactos o incompletos. Usted deberá informar a CCM de los cambios que se deban hacer a sus Datos Personales, cuando dichos cambios solo sean de su conocimiento.<br>
		+ El derecho de Cancelación consiste en.- que sus Datos Personales sean dados de baja total o parcialmente de las bases de datos de CCM. Esta solicitud dará lugar a un periodo de bloqueo tras el cual procederá la supresión de los datos. Existen casos en los que la cancelación no será posible en términos de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares y otras disposiciones legales aplicables.<br>
		+ El derecho de Oposición consiste en.- oponerse por causa legítima al tratamiento de sus Datos Personales por parte de CCM.</p>
		<p>En los casos que desee dejar de recibir ciertos comunicados de CCM, en dichos comunicados se incluirá la opción para salir de la lista de envío y dejar de recibirlos.</p>
		<p><b>CAMBIOS AL AVISO DE PRIVACIDAD</b></p>
		<p>Las condiciones aquí establecidas rigen el uso de toda la información recabada en nuestros sitios Web mientras el Aviso de Privacidad esté vigente. CCM se reserva el derecho de modificar o enmendar este Aviso, en cualquier momento, por lo que le rogamos visitar esta página frecuentemente ya que en ella se publicará del Aviso de Privacidad vigente. Los cambios al Aviso de Privacidad surten efecto al momento en que los mismos se publican en este sitio Web y usted continua haciendo uso de los sitios Web de CCM.</p>
		<p>Si sus datos personales fueron recabados por otros medios (distintos a en nuestro sitio Web) se le hará llegar la notificación correspondiente de los cambios o modificaciones al correo electrónico o domicilio que nos haya proporcionado o de la manera que CCM considere adecuada, siempre salvaguardando su derecho a la privacidad y a la autodeterminación informativa.</p>
		<p><b>CONSENTIMIENTO</b></p>
		<p>Al proporcionar cualquier tipo de información, incluyendo Datos Personales, a través de los sitios Web de CCM o de los formatos mediante los cuales se recaben dichos Datos Personales, usted expresamente: (i) acepta las condiciones contenidas en el presente Aviso de Privacidad; (ii) está de acuerdo en que la información proporcionada por usted pueda almacenarse, usarse y, en general, tratarse para los fines que se señalan, incluso para fines comerciales y de promoción, siempre que haya dado su autorización en los formatos correspondientes; (iii) otorga a CCM autorización para obtener, compilar, almacenar, compartir, comunicar, transmitir y usar tal información de cualquier manera o forma, de conformidad con las condiciones establecidas en el presente y las leyes aplicables. Usted reconoce que toda la información proporcionada por usted es verdadera y puesta al día. Si desea verificar, modificar o complementar la información aquí proporcionada, le rogamos iniciar sesión utilizando su usuario y contraseña.</p>
		<p><b>CONTACTO</b></p>
		<p>Preguntas, comentarios, ejercicio de derechos al:</p>
		<p>Departamento de Protección de Datos Personales de CCM<br>
		Correo electrónico: contacto@tiendaccm.mx</p>
		<p>Para consultas en relación con nuestros productos o servicios le pedimos dirigirse a nuestra página de contacto donde con mucho gusto atenderemos sus inquietudes.</p>
	</div>
		<div class="modal-footer">
		<a id="no_acepto" class="modal-action modal-close waves-effect waves-green btn-flat ">No Acepto</a>
		<a id="acepto" class="modal-action modal-close waves-effect waves-green btn-flat ">Acepto</a>
	</div>
</div>